### ISSUE TITLE
make build resulting in error

### ISSUE THREAD

**Issue by yyefet** [rad-security/kbom#58]
GO Version
go version go1.20.3 linux/amd64

OS
Red Hat Enterprise Linux 8.6 (Ootpa)

Command:
make build

Error:
# runtime
../../.go/src/runtime/security_linux.go:14:9: undefined: secureMode
../../.go/src/runtime/security_unix.go:55:17: undefined: fcntl

**Comment by pawelkowalak** [comment]
Hi, thanks for your report. It works both on Mac OS and Debian, but we're unable to check it on RedHat. We'd need more info about your setup. Did you install Go from official website? When upgrading Go from tarball are you removing old installation first? (this could be broken Go environment). Do you successfully build any other Go projects? Unfortunately there are not many good search results when looking for this error. Let us know if you found what was the problem, it might be useful for other users as well.

**Comment by pawelkowalak** [comment]
Btw I've checked on CentOS 8 with Go 1.20.5 and it builds fine.

**Comment by mateuszdyminski** [comment]
Closing as it seems that it's not valid anymore
